# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6bd4ab269089c4601d7bae22df819d6ecd1af42dc87d79a84b43fb39b7fdeddb60927da4d43b687cb26907c9f3f56a5a5a62aa7d42af419d80f8087854e654f

test:
  secret_key_base: f5337b252e1b550ffc31403a87a5bf525aabe49f710f12ab851052c247c622f418a4bb83bd7b33d67ff059a499114e16e41403d956a72441cc0fed638a3c2824

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
